name: sentence-counter-tool
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/sentence-counter-tool
  original_url: https://huggingface.co/spaces/Chris4K/sentence-counter-tool

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
